import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/authentication');
  await page.getByText('Enter email address').click();
  await page.getByLabel('Enter email address').fill('ownerTest@ownertest.com');
  await page.getByLabel('Enter email address').press('Tab');
  await page.getByLabel('Enter your password').fill('ownerTest12345');
  await page.getByLabel('Hide password').click();
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Roles' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByLabel('Role Name').click();
  await page.getByLabel('Role Name').fill('TestRole');
  await page.getByLabel('Role Description').click();
  await page.getByLabel('Role Description').fill('Test Role entered by playwright');
  await page.getByRole('button', { name: 'Add Role' }).click();
  await page.locator('.mat-mdc-paginator-touch-target').click();
  await page.getByRole('option', { name: '8' }).click();
  await page.getByRole('row', { name: 'TestRole Test Role entered by' }).getByRole('button').click();
  await page.getByRole('menuitem', { name: ' Edit' }).click();
  await page.getByLabel('Role Name').click();
  await page.getByLabel('Role Name').fill('TestRole-Updated');
  await page.getByLabel('Role Description').click();
  await page.getByLabel('Role Description').click();
  await page.getByLabel('Role Description').press('End');
  await page.getByLabel('Role Description').fill('Test Role entered by playwright (updated)');
  await page.getByRole('button', { name: 'Update Role' }).click();
  await page.locator('.mat-mdc-paginator-touch-target').click();
  await page.getByRole('option', { name: '8' }).click();
  await page.getByRole('link', { name: 'Events' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByLabel('Event Name').click();
  await page.getByLabel('Event Name').fill('Kids Krave');
  await page.getByLabel('Event Name').press('Tab');
  await page.getByLabel('Event Description').fill('Kids ages 8-12 can learn to kick butt!');
  await page.getByRole('button', { name: 'Add Event' }).click();
});